version: "3.8"
services:
  video-downloader:
    build: .
    container_name: video-downloader
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
    restart: unless-stopped
